const employees = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul.sharma@talentflow.com",
    role: "Frontend Developer",
    experience: 4,
    skills: ["React", "JavaScript", "Redux", "Tailwind CSS"],
    availability: "Available",
  },
  {
    id: 2,
    name: "Priya Deshmukh",
    email: "priya.deshmukh@talentflow.com",
    role: "Backend Developer",
    experience: 5,
    skills: ["Java", "Spring Boot", "MySQL", "REST API"],
    availability: "Assigned",
  },
  {
    id: 3,
    name: "Amit Patil",
    email: "amit.patil@talentflow.com",
    role: "Full Stack Developer",
    experience: 6,
    skills: ["React", "Node.js", "MongoDB", "Express"],
    availability: "Available",
  },
  {
    id: 4,
    name: "Sneha Kulkarni",
    email: "sneha.kulkarni@talentflow.com",
    role: "UI Developer",
    experience: 3,
    skills: ["HTML", "CSS", "JavaScript", "React"],
    availability: "Available",
  },
  {
    id: 5,
    name: "Vikram Joshi",
    email: "vikram.joshi@talentflow.com",
    role: "Backend Developer",
    experience: 7,
    skills: ["Node.js", "Express", "MongoDB", "AWS"],
    availability: "Assigned",
  },
  {
    id: 6,
    name: "Neha Pawar",
    email: "neha.pawar@talentflow.com",
    role: "Frontend Developer",
    experience: 3,
    skills: ["React", "TypeScript", "Redux", "CSS"],
    availability: "Available",
  },
  {
    id: 7,
    name: "Akash Jadhav",
    email: "akash.jadhav@talentflow.com",
    role: "DevOps Engineer",
    experience: 5,
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins"],
    availability: "Available",
  },
  {
    id: 8,
    name: "Pooja More",
    email: "pooja.more@talentflow.com",
    role: "QA Engineer",
    experience: 4,
    skills: ["Jest", "Cypress", "Selenium", "API Testing"],
    availability: "Assigned",
  },
  {
    id: 9,
    name: "Rohan Desai",
    email: "rohan.desai@talentflow.com",
    role: "Full Stack Developer",
    experience: 5,
    skills: ["React", "Node.js", "PostgreSQL", "Docker"],
    availability: "Available",
  },
  {
    id: 10,
    name: "Anjali Patil",
    email: "anjali.patil@talentflow.com",
    role: "Frontend Developer",
    experience: 2,
    skills: ["React", "JavaScript", "HTML", "CSS"],
    availability: "Available",
  },
  {
    id: 11,
    name: "Saurabh Kulkarni",
    email: "saurabh.kulkarni@talentflow.com",
    role: "Java Developer",
    experience: 6,
    skills: ["Java", "Spring Boot", "Hibernate", "PostgreSQL"],
    availability: "Assigned",
  },
  {
    id: 12,
    name: "Megha Shinde",
    email: "megha.shinde@talentflow.com",
    role: "Business Analyst",
    experience: 5,
    skills: ["Requirements Analysis", "SQL", "JIRA", "Agile"],
    availability: "Available",
  },
  {
    id: 13,
    name: "Kunal Chavan",
    email: "kunal.chavan@talentflow.com",
    role: "Cloud Engineer",
    experience: 4,
    skills: ["AWS", "Azure", "Terraform", "Docker"],
    availability: "Available",
  },
  {
    id: 14,
    name: "Riya Desai",
    email: "riya.desai@talentflow.com",
    role: "UI/UX Developer",
    experience: 4,
    skills: ["Figma", "HTML", "CSS", "JavaScript"],
    availability: "Assigned",
  },
  {
    id: 15,
    name: "Nikhil Pawar",
    email: "nikhil.pawar@talentflow.com",
    role: "Database Developer",
    experience: 7,
    skills: ["SQL", "MySQL", "PostgreSQL", "Oracle"],
    availability: "Available",
  },
  {
    id: 16,
    name: "Swati Joshi",
    email: "swati.joshi@talentflow.com",
    role: "Frontend Developer",
    experience: 5,
    skills: ["React", "Redux Toolkit", "JavaScript", "Tailwind CSS"],
    availability: "Assigned",
  },
  {
    id: 17,
    name: "Aditya More",
    email: "aditya.more@talentflow.com",
    role: "Software Engineer",
    experience: 3,
    skills: ["Python", "Django", "REST API", "PostgreSQL"],
    availability: "Available",
  },
  {
    id: 18,
    name: "Isha Patil",
    email: "isha.patil@talentflow.com",
    role: "QA Automation Engineer",
    experience: 5,
    skills: ["Selenium", "Cypress", "JavaScript", "Jenkins"],
    availability: "Available",
  },
  {
    id: 19,
    name: "Manish Shinde",
    email: "manish.shinde@talentflow.com",
    role: "Technical Lead",
    experience: 9,
    skills: ["React", "Node.js", "AWS", "System Design"],
    availability: "Assigned",
  },
  {
    id: 20,
    name: "Aarti Deshmukh",
    email: "aarti.deshmukh@talentflow.com",
    role: "React Developer",
    experience: 4,
    skills: ["React", "Redux Toolkit", "Axios", "Tailwind CSS"],
    availability: "Available",
  },
];

export const fetchEmployees = async () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(employees);
    }, 800);
  });
};